# Generated by Django 4.1.13 on 2024-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_action_action_blog_action_created_2bb3ab_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
